#pragma once
#ifndef __DEVICE_CONTROL_H
#define __DEVICE_CONTROL_H

#include "driver.h"

#define IOCTL_PROXY_TCP_INIT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROXY_TCP_SET_INCLUDED	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x002, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROXY_TCP_SET_EXCLUDED	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x003, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROXY_TCP_SET_PORT		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x004, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROXY_TCP_ADD_PROCESS		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x005, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROXY_TCP_DESTROY			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x006, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif
